config/routes.rb
Rails.application.routes.draw do
  get 'documentation/show'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      unlocks: 'users/unlocks'
  }

  devise_scope :user do
    get '/reset_token', to: 'users/registrations#reset_token'
  end

  resource :dashboard, only: [:show], controller: 'dashboard'
  resources :cards, constraints: lambda {|request| request.xhr?}
  resource :documentation, controller: 'documentation'

  resources :devices, only: [:index, :create, :update, :destroy] do
    resources :fields, only: [:index, :create, :update, :destroy], constraints: lambda {|request| request.xhr? or request.url.match(/\/fields\/[a-zA-Z0-p-]+\/values(\/[a-zA-Z0-p-]+)?.json/)} do
      member do
        delete '/clear', to: 'fields#clear'
      end
      resources :values, only: [:index, :show, :create], constraints: lambda {|request| request.format == :json}
    end
  end

  resources :scenarios
  resources :notifications, only: [:update] do
    delete 'dismiss_all', on: :collection
    get 'history', on: :collection
  end

  root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    alias_action :create, :read, :update, :destroy, to: :crud

    can :crud, Device, user_id: user.id
    can :crud, Field, device: { user_id: user.id }
    can :clear, Field, device: { user_id: user.id }
    can :crud, Value, field: { device: { user_id: user.id } }
    can :crud, Card, user_id: user.id
    can :crud, Scenario, user_id: user.id
    can :update, Notification, user_id: user.id
    can :dismiss_all, Notification, user_id: user.id
    can :history, Notification, user_id: user.id
    can :show, :dashboard
    can :show, :documentation
  end
end

app/models/action.rb
class Action < ApplicationRecord
  belongs_to :scenario
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :fields
  before_create :check_title
  before_destroy { fields.clear }

  def check_title
    self.title = 'Default title' if title == ''
  end

end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :scenario
  belongs_to :field

  def check
    case self.field_position
      when 'below'
        return self.field.values.order(:created_at).last.value < self.field_threshold
      when 'equal'
        return self.field.values.order(:created_at).last.value == self.field_threshold
      when 'over'
        return self.field.values.order(:created_at).last.value > self.field_threshold
      else
        return false
    end
  end

end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :user
  has_many :fields, dependent: :destroy

  scope :enabled, -> { where enabled: true}

  before_create :check_name

  def check_name
    self.name = 'Default device name' if name == ''
  end
end

app/models/field.rb
class Field < ApplicationRecord
  belongs_to :device
  has_many :values, dependent: :destroy
  has_and_belongs_to_many :cards
  has_many :conditions


  scope :enabled, -> { where enabled: true}

  before_create :check_name
  before_destroy { cards.clear }

  def check_name
    self.name = 'Default field name' if name == ''
  end

  def last_value
    self.values.order(:created_at).last
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user

  scope :unread, -> { where read: false }

  def unread?
    self.read != true
  end

end

app/models/scenario.rb
class Scenario < ApplicationRecord
  belongs_to :user
  has_many :conditions, dependent: :destroy
  has_many :actions, dependent: :destroy

  scope :concern_field, ->(field) { Scenario.includes(:conditions).where(conditions: {field_id: field.id}) }
  scope :enabled, -> { where enabled: true }

  include TextFormatHelper

  def check
    self.conditions.map {|c| c.check}.delete_if {|v| v == false}.size == self.conditions.size
  end

  def execute
    p "execute scenario #{self.id}"
    self.actions.each do |a|
      if a.action_type == 'email'
        ScenarioMailer.notify_email(a).deliver_later
      elsif a.action_type == 'notification'
        scenario = a.scenario
        scenario.user.notifications.create(title: reformat(a.notification_title, scenario), text: reformat(a.notification_text, scenario), level: a.notification_level)
      end
    end
    return
  end

end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable

  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable,
         :confirmable, :lockable

  has_many :devices, dependent: :destroy
  has_many :cards, dependent: :destroy
  has_many :scenarios, dependent: :destroy
  has_many :notifications, dependent: :destroy

  def reset_authentication_token!
    self.authentication_token = nil
    save
  end

end

app/models/value.rb
class Value < ApplicationRecord
  belongs_to :field

  after_create :check_scenarios

  def check_scenarios
    self.field.device.user.scenarios.enabled.concern_field(self.field).each do |scenario|
      scenario.execute if scenario.check
    end
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  # POST /devices
  # POST /devices.json
  def create
    # @device = current_user.devices.create(device_params)
    @device.save
    respond_to do |format|
      format.html {render partial: 'device_row', locals: {device: @device}}
      format.json {render :show, status: :created, location: @device}
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    @device.update(device_params)
    respond_to do |format|
      format.html {head :ok}
      format.json {render :show, status: :created, location: @device}
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    id = @device.id
    @device.destroy
    render json: {id: id}
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_device
    @device = Device.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def device_params
    params.fetch(:device, {}).permit(:name, :enabled)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper

  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = render partial: 'users/error_explanation', locals: {sentence: sentence, messages: messages}

    html.html_safe
  end

end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/helpers/token_helper.rb
module TokenHelper
end

app/helpers/values_helper.rb
module ValuesHelper
end

app/views/devices/_device_row.html.erb
<tr id="<%= device.id %>">
  <td><%= device.id %></td>
  <td><%= device.name %></td>
  <td>
    <div class="switch no-margin">
      <input class="switch-input device-state-switch" id="device-state-switch-<%= device.id %>" type="checkbox" <%= device.enabled ? 'checked' : nil %> data-url="<%= device_path(device) %>">
      <label class="switch-paddle" for="device-state-switch-<%= device.id %>">
        <span class="switch-active" aria-hidden="true">Yes</span>
        <span class="switch-inactive" aria-hidden="true">No</span>
      </label>
    </div>
  </td>
  <td>
    <div class="button-group no-margin">
      <button class="button info edit-device-btn" data-url="<%= device_fields_path(device) %>">Edit</button>
      <button class="button alert delete-device-btn" data-url="<%= device_path(device) %>">Delete</button>
    </div>
  </td>
</tr>

app/views/devices/index.html.erb
<div class="table-scroll">
  <table class="no-margin" id="devices">
    <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Enabled?</th>
      <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <% @devices.each do |device| %>
      <%= render partial: 'devices/device_row', locals: {device: device} %>
    <% end %>

    <tr id="create-device-line">
      <td></td>
      <td>
        <input class="no-margin" id="new-device-name" type="text" placeholder="Name">
      </td>
      <td>
        <div class="switch disabled no-margin">
          <input class="switch-input" id="switch-create-device" type="checkbox" checked disabled>
          <label class="switch-paddle" for="switch-create-device">
            <span class="switch-active" aria-hidden="true">Yes</span>
            <span class="switch-inactive" aria-hidden="true">No</span>
          </label>
        </div>
      </td>
      <td>
        <button class="button success" id="create-device-btn" data-url="<%= devices_path %>">Create</button>
      </td>
    </tr>
    </tbody>
  </table>
</div>