config/routes.rb
Rails.application.routes.draw do
  get 'documentation/show'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      unlocks: 'users/unlocks'
  }

  devise_scope :user do
    get '/reset_token', to: 'users/registrations#reset_token'
  end

  resource :dashboard, only: [:show], controller: 'dashboard'
  resources :cards, constraints: lambda {|request| request.xhr?}
  resource :documentation, controller: 'documentation'

  resources :devices, only: [:index, :create, :update, :destroy] do
    resources :fields, only: [:index, :create, :update, :destroy], constraints: lambda {|request| request.xhr? or request.url.match(/\/fields\/[a-zA-Z0-p-]+\/values(\/[a-zA-Z0-p-]+)?.json/)} do
      member do
        delete '/clear', to: 'fields#clear'
      end
      resources :values, only: [:index, :show, :create], constraints: lambda {|request| request.format == :json}
    end
  end

  resources :scenarios
  resources :notifications, only: [:update] do
    delete 'dismiss_all', on: :collection
    get 'history', on: :collection
  end

  root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    alias_action :create, :read, :update, :destroy, to: :crud

    can :crud, Device, user_id: user.id
    can :crud, Field, device: { user_id: user.id }
    can :clear, Field, device: { user_id: user.id }
    can :crud, Value, field: { device: { user_id: user.id } }
    can :crud, Card, user_id: user.id
    can :crud, Scenario, user_id: user.id
    can :update, Notification, user_id: user.id
    can :dismiss_all, Notification, user_id: user.id
    can :history, Notification, user_id: user.id
    can :show, :dashboard
    can :show, :documentation
  end
end

app/models/action.rb
class Action < ApplicationRecord
  belongs_to :scenario
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :fields
  before_create :check_title
  before_destroy { fields.clear }

  def check_title
    self.title = 'Default title' if title == ''
  end

end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :scenario
  belongs_to :field

  def check
    case self.field_position
      when 'below'
        return self.field.values.order(:created_at).last.value < self.field_threshold
      when 'equal'
        return self.field.values.order(:created_at).last.value == self.field_threshold
      when 'over'
        return self.field.values.order(:created_at).last.value > self.field_threshold
      else
        return false
    end
  end

end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :user
  has_many :fields, dependent: :destroy

  scope :enabled, -> { where enabled: true}

  before_create :check_name

  def check_name
    self.name = 'Default device name' if name == ''
  end
end

app/models/field.rb
class Field < ApplicationRecord
  belongs_to :device
  has_many :values, dependent: :destroy
  has_and_belongs_to_many :cards
  has_many :conditions


  scope :enabled, -> { where enabled: true}

  before_create :check_name
  before_destroy { cards.clear }

  def check_name
    self.name = 'Default field name' if name == ''
  end

  def last_value
    self.values.order(:created_at).last
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user

  scope :unread, -> { where read: false }

  def unread?
    self.read != true
  end

end

app/models/scenario.rb
class Scenario < ApplicationRecord
  belongs_to :user
  has_many :conditions, dependent: :destroy
  has_many :actions, dependent: :destroy

  scope :concern_field, ->(field) { Scenario.includes(:conditions).where(conditions: {field_id: field.id}) }
  scope :enabled, -> { where enabled: true }

  include TextFormatHelper

  def check
    self.conditions.map {|c| c.check}.delete_if {|v| v == false}.size == self.conditions.size
  end

  def execute
    p "execute scenario #{self.id}"
    self.actions.each do |a|
      if a.action_type == 'email'
        ScenarioMailer.notify_email(a).deliver_later
      elsif a.action_type == 'notification'
        scenario = a.scenario
        scenario.user.notifications.create(title: reformat(a.notification_title, scenario), text: reformat(a.notification_text, scenario), level: a.notification_level)
      end
    end
    return
  end

end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable

  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable,
         :confirmable, :lockable

  has_many :devices, dependent: :destroy
  has_many :cards, dependent: :destroy
  has_many :scenarios, dependent: :destroy
  has_many :notifications, dependent: :destroy

  def reset_authentication_token!
    self.authentication_token = nil
    save
  end

end

app/models/value.rb
class Value < ApplicationRecord
  belongs_to :field

  after_create :check_scenarios

  def check_scenarios
    self.field.device.user.scenarios.enabled.concern_field(self.field).each do |scenario|
      scenario.execute if scenario.check
    end
  end
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  wrap_parameters false

  def new
    render layout: false
  end

  def create
    scenario = current_user.scenarios.create(scenario_params)
    params[:scenario][:conditions].each do |c|
      scenario.conditions.create(field_id: c[:field_id], field_position: c[:position], field_threshold: c[:threshold])
    end
    params[:scenario][:actions].each do |a|
      scenario.actions.create(action_type: a[:type], email_object: a[:email_object], email_text: a[:email_text], notification_title: a[:notification_title], notification_text: a[:notification_text], notification_level: a[:notification_level])
    end
    respond_to do |format|
      format.html {render partial: 'scenario_row', locals: {scenario: scenario}}
      format.json {render :show, status: :created, location: scenario}
    end
  end

  def edit
    respond_to do |format|
      format.json {render file: 'scenarios/edit.json'}
    end
  end

  def update
    @scenario.update(scenario_params)
    unless scenario_params[:enabled] != nil
      @scenario.conditions.clear
      @scenario.actions.clear
      params[:scenario][:conditions].each do |c|
        @scenario.conditions.create(field_id: c[:field_id], field_position: c[:position], field_threshold: c[:threshold])
      end
      params[:scenario][:actions].each do |a|
        @scenario.actions.create(action_type: a[:type], email_object: a[:email_object], email_text: a[:email_text])
      end
    end
  end

  def destroy
    id = @scenario.id
    @scenario.destroy
    render json: {id: id}
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_scenario
    @scenario = Scenario.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def scenario_params
    params.require(:scenario).permit(:name, :enabled, conditions: [], actions: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper

  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = render partial: 'users/error_explanation', locals: {sentence: sentence, messages: messages}

    html.html_safe
  end

end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/helpers/token_helper.rb
module TokenHelper
end

app/helpers/values_helper.rb
module ValuesHelper
end

app/views/scenarios/_scenario_row.html.erb
<tr id="<%= scenario.id %>">
  <td><%= scenario.id %></td>
  <td><%= scenario.name %></td>
  <td>
    <div class="switch no-margin">
      <input class="switch-input scenario-state-switch" id="scenario-state-switch-<%= scenario.id %>" type="checkbox" <%= scenario.enabled ? 'checked' : nil %> data-url="<%= scenario_path(scenario) %>">
      <label class="switch-paddle" for="scenario-state-switch-<%= scenario.id %>">
        <span class="switch-active" aria-hidden="true">Yes</span>
        <span class="switch-inactive" aria-hidden="true">No</span>
      </label>
    </div>
  </td>
  <td>
    <div class="button-group no-margin">
      <button class="button info edit-scenario-btn" data-url="<%= edit_scenario_path(scenario) %>">Edit</button>
      <button class="button alert delete-scenario-btn" data-url="<%= scenario_path(scenario) %>">Delete</button>
    </div>
  </td>
</tr>

app/views/scenarios/edit.html.erb
<div class="grid-y">
  <div class="cell shrink title-cell">
    <h5 style="margin: 0">Edit Scenario</h5>
    <!--<button class="close-button" data-close aria-label="Close modal" type="button">-->
    <!--<span aria-hidden="true">&times;</span>-->
    <!--</button>-->
  </div>
  <div class="cell shrink" style="margin-top: 16px">

    <ul class="tabs" data-tabs id="example-tabs">
      <li class="tabs-title is-active"><a href="#panel1" aria-selected="true">Name</a></li>
      <li class="tabs-title"><a data-tabs-target="panel2" href="#panel2">Conditions</a></li>
      <li class="tabs-title"><a data-tabs-target="panel3" href="#panel3">Actions</a></li>
    </ul>

    <div class="tabs-content" data-tabs-content="example-tabs">
      <div class="tabs-panel is-active" id="panel1">
        <div class="input-group">
          <span class="input-group-label">Name</span>
          <input class="input-group-field" id="scenario-name" type="text" placeholder="Name", value="<%= @scenario.name %>">
        </div>
        <button class="button no-margin next-tab">Next</button>
      </div>

      <div class="tabs-panel" id="panel2">
        <div class="input-group">
          <span class="input-group-label">Device</span>
          <%= select_tag(:scenario_device_id, options_for_select(current_user.devices.map {|device| [device.name, device.id]}.prepend(['Select a device', 0]), disabled: [0], selected: [0]), class: 'input-group-field') %>
        </div>

        <div class="input-group">
          <span class="input-group-label">Fields</span>
          <select class="input-group-field" id="scenario_field_id">
            <option selected disabled>Select a field</option>
          </select>
        </div>

        <div class="input-group">
          <span class="input-group-label">Position</span>
          <%= select_tag(:scenario_field_position, options_for_select([['Over', 'over'], ['Equal', 'equal'], ['Below', 'below']].prepend(['Select position', 0]), disabled: [0], selected: [0]), class: 'input-group-field') %>

          <span class="input-group-label" style="margin-left: 16px">Threshold</span>
          <input class="input-group-field" id="scenario_field_threshold" type="number" placeholder="0">
        </div>

        <button class="button" id="add-condition-btn">Add</button>

        <ul class="custom-list" id="conditions">
          <% if @scenario.conditions %>
            <% @scenario.conditions.each do |c| %>
              <li id="<%= c.id %>">
                <button class="delete-condition-btn" type="button" style="margin-right: 5px" data-id="<%= c.id %>">
                  <i class="fas fa-times" aria-hidden="true"></i>
                </button>
                <%= "#{c.field.device.name}:#{c.field.name} is #{c.field_position} #{c.field_threshold}" %>
              </li>
            <% end %>
          <% else %>
            <li>No conditions</li>
          <% end %>
        </ul>

        <button class="button no-margin next-tab">Next</button>
      </div>

      <div class="tabs-panel" id="panel3">
        <div class="input-group">
          <span class="input-group-label">Action</span>
          <%= select_tag(:action_type, options_for_select([['Notification', 'notification'], ['Email', 'email']].prepend(['Select an action', 0]), disabled: [0], selected: [0]), class: 'input-group-field') %>
        </div>

        <div class="action-selector hide" id="notification">

          <div class="input-group">
            <span class="input-group-label">Title</span>
            <input class="input-group-field" id="notification_title" type="text" placeholder="Title">
          </div>

          <div class="input-group">
            <span class="input-group-label">Text</span>
            <textarea class="input-group-field" id="notification_text" placeholder="Text"></textarea>
          </div>

          <div class="input-group">
            <span class="input-group-label">Level</span>
            <%= select_tag(:notification_level, options_for_select([['Info', 'info'], ['Success', 'success'], ['Warning', 'warning'], ['Alert', 'alert']].prepend(['Select level', 0]), disabled: [0], selected: [0]), class: 'input-group-field') %>
          </div>
        </div>

        <div class="action-selector hide" id="email">

          <div class="input-group">
            <span class="input-group-label">Object</span>
            <input class="input-group-field" id="email_object" type="text" placeholder="Object">
          </div>

          <div class="input-group">
            <span class="input-group-label">Text</span>
            <textarea class="input-group-field" id="email_text" placeholder="Text"></textarea>
          </div>
        </div>

        <button class="button" id="add-action-btn">Add</button>

        <ul class="custom-list" id="actions">
          <% if @scenario.actions %>
            <% @scenario.actions.each do |a| %>
              <li id="<%= a.id %>">
                <button class="delete-action-btn" type="button" style="margin-right: 5px" data-id="<%= a.id %>">
                  <i class="fas fa-times" aria-hidden="true"></i>
                </button>
                <% if a.action_type == 'email' %>
                  <%= "Email : #{a.email_object}" %>
                <% else %>
                  <%= "Notification : #{a.notification_level} : #{a.notification_title}" %>
                <% end %>
              </li>
            <% end %>
          <% else %>
            <li>No actions</li>
          <% end %>
        </ul>

        <button class="button no-margin" id="update-scenario-btn" data-url="<%= scenario_path(@scenario) %>">Save</button>
      </div>
    </div>

  </div>
</div>

app/views/scenarios/index.html.erb
<div class="table-scroll">
  <table class="no-margin" id="scenarios">
    <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Enabled?</th>
      <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <% @scenarios.each do |scenario| %>
      <%= render partial: 'scenarios/scenario_row', locals: {scenario: scenario} %>
    <% end %>

    </tbody>
  </table>
</div>

app/views/scenarios/new.html.erb
<div class="grid-y">
  <div class="cell shrink title-cell">
    <h5 style="margin: 0">New Scenario</h5>
    <!--<button class="close-button" data-close aria-label="Close modal" type="button">-->
    <!--<span aria-hidden="true">&times;</span>-->
    <!--</button>-->
  </div>
  <div class="cell shrink" style="margin-top: 16px">

    <ul class="tabs" data-tabs id="example-tabs">
      <li class="tabs-title is-active"><a href="#panel1" aria-selected="true">Name</a></li>
      <li class="tabs-title"><a data-tabs-target="panel2" href="#panel2">Conditions</a></li>
      <li class="tabs-title"><a data-tabs-target="panel3" href="#panel3">Actions</a></li>
    </ul>

    <div class="tabs-content" data-tabs-content="example-tabs">
      <div class="tabs-panel is-active" id="panel1">
        <div class="input-group">
          <span class="input-group-label">Name</span>
          <input class="input-group-field" id="scenario-name" type="text" placeholder="Name">
        </div>
        <button class="button no-margin next-tab">Next</button>
      </div>

      <div class="tabs-panel" id="panel2">
        <div class="input-group">
          <span class="input-group-label">Device</span>
          <%= select_tag(:scenario_device_id, options_for_select(current_user.devices.map {|device| [device.name, device.id]}.prepend(['Select a device', 0]), disabled: [0], selected: [0]), class: 'input-group-field') %>
        </div>

        <div class="input-group">
          <span class="input-group-label">Fields</span>
          <select class="input-group-field" id="scenario_field_id">
            <option selected disabled>Select a field</option>
          </select>
        </div>

        <div class="input-group">
          <span class="input-group-label">Position</span>
          <%= select_tag(:scenario_field_position, options_for_select([['Over', 'over'], ['Equal', 'equal'], ['Below', 'below']].prepend(['Select position', 0]), disabled: [0], selected: [0]), class: 'input-group-field') %>

          <span class="input-group-label" style="margin-left: 16px">Threshold</span>
          <input class="input-group-field" id="scenario_field_threshold" type="number" placeholder="0">
        </div>

        <button class="button" id="add-condition-btn">Add</button>

        <ul class="custom-list" id="conditions">
          <li>No conditions</li>
        </ul>

        <button class="button no-margin next-tab">Next</button>
      </div>

      <div class="tabs-panel" id="panel3">
        <div class="input-group">
          <span class="input-group-label">Action</span>
          <%= select_tag(:action_type, options_for_select([['Notification', 'notification'], ['Email', 'email']].prepend(['Select an action', 0]), disabled: [0], selected: [0]), class: 'input-group-field') %>
        </div>

        <div class="action-selector hide" id="notification">

          <div class="input-group">
            <span class="input-group-label">Title</span>
            <input class="input-group-field" id="notification_title" type="text" placeholder="Title">
          </div>

          <div class="input-group">
            <span class="input-group-label">Text</span>
            <textarea class="input-group-field" id="notification_text" placeholder="Text"></textarea>
          </div>

          <div class="input-group">
            <span class="input-group-label">Level</span>
            <%= select_tag(:notification_level, options_for_select([['Info', 'info'], ['Success', 'success'], ['Warning', 'warning'], ['Alert', 'alert']].prepend(['Select level', 0]), disabled: [0], selected: [0]), class: 'input-group-field') %>
          </div>
        </div>

        <div class="action-selector hide" id="email">

          <div class="input-group">
            <span class="input-group-label">Object</span>
            <input class="input-group-field" id="email_object" type="text" placeholder="Object">
          </div>

          <div class="input-group">
            <span class="input-group-label">Text</span>
            <textarea class="input-group-field" id="email_text" placeholder="Text"></textarea>
          </div>
        </div>

        <button class="button" id="add-action-btn">Add</button>

        <ul class="custom-list" id="actions">
          <li>No actions</li>
        </ul>

        <button class="button no-margin" id="create-scenario-btn" data-url="<%= scenarios_path %>">Create</button>
      </div>
    </div>

  </div>
</div>