config/routes.rb
Rails.application.routes.draw do
  get 'documentation/show'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      unlocks: 'users/unlocks'
  }

  devise_scope :user do
    get '/reset_token', to: 'users/registrations#reset_token'
  end

  resource :dashboard, only: [:show], controller: 'dashboard'
  resources :cards, constraints: lambda {|request| request.xhr?}
  resource :documentation, controller: 'documentation'

  resources :devices, only: [:index, :create, :update, :destroy] do
    resources :fields, only: [:index, :create, :update, :destroy], constraints: lambda {|request| request.xhr? or request.url.match(/\/fields\/[a-zA-Z0-p-]+\/values(\/[a-zA-Z0-p-]+)?.json/)} do
      member do
        delete '/clear', to: 'fields#clear'
      end
      resources :values, only: [:index, :show, :create], constraints: lambda {|request| request.format == :json}
    end
  end

  resources :scenarios
  resources :notifications, only: [:update] do
    delete 'dismiss_all', on: :collection
    get 'history', on: :collection
  end

  root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    alias_action :create, :read, :update, :destroy, to: :crud

    can :crud, Device, user_id: user.id
    can :crud, Field, device: { user_id: user.id }
    can :clear, Field, device: { user_id: user.id }
    can :crud, Value, field: { device: { user_id: user.id } }
    can :crud, Card, user_id: user.id
    can :crud, Scenario, user_id: user.id
    can :update, Notification, user_id: user.id
    can :dismiss_all, Notification, user_id: user.id
    can :history, Notification, user_id: user.id
    can :show, :dashboard
    can :show, :documentation
  end
end

app/models/action.rb
class Action < ApplicationRecord
  belongs_to :scenario
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :fields
  before_create :check_title
  before_destroy { fields.clear }

  def check_title
    self.title = 'Default title' if title == ''
  end

end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :scenario
  belongs_to :field

  def check
    case self.field_position
      when 'below'
        return self.field.values.order(:created_at).last.value < self.field_threshold
      when 'equal'
        return self.field.values.order(:created_at).last.value == self.field_threshold
      when 'over'
        return self.field.values.order(:created_at).last.value > self.field_threshold
      else
        return false
    end
  end

end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :user
  has_many :fields, dependent: :destroy

  scope :enabled, -> { where enabled: true}

  before_create :check_name

  def check_name
    self.name = 'Default device name' if name == ''
  end
end

app/models/field.rb
class Field < ApplicationRecord
  belongs_to :device
  has_many :values, dependent: :destroy
  has_and_belongs_to_many :cards
  has_many :conditions


  scope :enabled, -> { where enabled: true}

  before_create :check_name
  before_destroy { cards.clear }

  def check_name
    self.name = 'Default field name' if name == ''
  end

  def last_value
    self.values.order(:created_at).last
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user

  scope :unread, -> { where read: false }

  def unread?
    self.read != true
  end

end

app/models/scenario.rb
class Scenario < ApplicationRecord
  belongs_to :user
  has_many :conditions, dependent: :destroy
  has_many :actions, dependent: :destroy

  scope :concern_field, ->(field) { Scenario.includes(:conditions).where(conditions: {field_id: field.id}) }
  scope :enabled, -> { where enabled: true }

  include TextFormatHelper

  def check
    self.conditions.map {|c| c.check}.delete_if {|v| v == false}.size == self.conditions.size
  end

  def execute
    p "execute scenario #{self.id}"
    self.actions.each do |a|
      if a.action_type == 'email'
        ScenarioMailer.notify_email(a).deliver_later
      elsif a.action_type == 'notification'
        scenario = a.scenario
        scenario.user.notifications.create(title: reformat(a.notification_title, scenario), text: reformat(a.notification_text, scenario), level: a.notification_level)
      end
    end
    return
  end

end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable

  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable,
         :confirmable, :lockable

  has_many :devices, dependent: :destroy
  has_many :cards, dependent: :destroy
  has_many :scenarios, dependent: :destroy
  has_many :notifications, dependent: :destroy

  def reset_authentication_token!
    self.authentication_token = nil
    save
  end

end

app/models/value.rb
class Value < ApplicationRecord
  belongs_to :field

  after_create :check_scenarios

  def check_scenarios
    self.field.device.user.scenarios.enabled.concern_field(self.field).each do |scenario|
      scenario.execute if scenario.check
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!

  load_and_authorize_resource

  layout false

  def show
    render partial: 'card', object: @card
  end

  def create
    # @card = current_user.cards.create(card_params)
    @card.save
    render partial: 'card', object: @card
  end

  def update
    @card.update(card_params)
    unless card_params[:field_ids]
      @card.fields.clear
    end
    render partial: 'card', object: @card
  end

  def destroy
    id = @card.id
    @card.destroy
    render json: {id: id}
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_card
    @card = Card.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def card_params
    params.fetch(:card, {}).permit(:title, :card_type, field_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper

  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = render partial: 'users/error_explanation', locals: {sentence: sentence, messages: messages}

    html.html_safe
  end

end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/helpers/token_helper.rb
module TokenHelper
end

app/helpers/values_helper.rb
module ValuesHelper
end

app/views/cards/_card.html.erb
<div class="card" id="<%= card.id %>" data-url="<%= card_path(card) %>">
  <div class="card-divider align-justify">
    <%= card.title %>
    <button class="menu-icon dark edit-card-btn" type="button" data-url="<%= edit_card_path(card) %>"></button>
  </div>
  <div class="card-section">
    <% if card.fields.first %>
      <% if card.card_type == 'graph' %>
        <%= line_chart card.fields.enabled.map {|field|
          {name: field.name, data: field.values.where('created_at > ?', Time.now - 1.week).pluck(:created_at, :value)}
        }, points: false, messages: {empty: "No data"} %>
      <% elsif card.card_type == 'value' %>
        <% card.fields.enabled.map {|field| field.last_value ? "#{field.name} : #{field.last_value.value} #{field.unit}" : "No data to show for #{field.name}"}.each do |data| %>
          <p><%= data %></p>
        <% end %>
      <% else %>
        <p>Invalid card type</p>
      <% end %>
    <% else %>
      <p>No data to show</p>
    <% end %>
  </div>
</div>

app/views/cards/_card_defer.html.erb
<div class="card" id="<%= card.id %>" data-url="<%= card_path(card) %>">
  <div class="card-divider align-justify">
    <%= card.title %>
    <button class="menu-icon dark edit-card-btn" type="button" data-url="<%= edit_card_path(card) %>"></button>
  </div>
  <div class="card-section">
    <% if card.fields.first %>
      <% if card.card_type == 'graph' %>
        <%= line_chart card.fields.enabled.map {|field|
          {name: field.name, data: field.values.where('created_at > ?', Time.now - 1.week).pluck(:created_at, :value)}
        }, points: false, messages: {empty: "No data"}, defer: true %>
      <% elsif card.card_type == 'value' %>
        <% card.fields.enabled.map {|field| field.last_value ? "#{field.name} : #{field.last_value.value} #{field.unit}" : "No data to show for #{field.name}"}.each do |data| %>
          <p><%= data %></p>
        <% end %>
      <% else %>
        <p>Invalid card type</p>
      <% end %>
    <% else %>
      <p>No data to show</p>
    <% end %>
  </div>
</div>

app/views/cards/edit.html.erb
<div class="grid-y">
  <div class="cell shrink title-cell">
    <h5 style="margin: 0">Edit Card</h5>
  </div>
  <div class="cell shrink" style="margin-top: 16px">

    <div class="input-group">
      <span class="input-group-label">Title</span>
      <input class="input-group-field" id="card-title" type="text" placeholder="Title" value="<%= @card.title %>">
    </div>

    <div class="input-group">
      <span class="input-group-label">Card type</span>
      <%= select_tag(:card_type, options_for_select([['Graph', 'graph'], ['Value', 'value']].prepend(['Select a type', '']), disabled: [''], selected: [@card.card_type || '']), class: 'input-group-field') %>
    </div>

    <label>Device
      <%= select_tag(:device_id, options_for_select(current_user.devices.map {|device| [device.name, device.id]}.prepend(['Select a device', 0]), disabled: [0], selected: [@card.fields.first ? @card.fields.first.device.id : 0]), {"data-selected_ids" => @card.fields.enabled.ids}) %>
    </label>

    <fieldset class="fieldset" style="margin-top: 0">
      <legend>Fields</legend>
      <div id="fields-boxes">
        <% if @card.fields.first %>
          <% @card.fields.first.device.fields.enabled.each do |field| %>
            <input type="checkbox" class="field-box" value="<%= field.id %>" <%= 'checked' if @card.fields.ids.include? field.id %>><label><%= field.name %></label>
          <% end %>
        <% else %>
          No available fields
        <% end %>
      </div>
    </fieldset>

    <button class="button" id="update-card-btn" data-url="<%= card_path(@card) %>" data-card_id="<%= @card.id %>">Update</button>
    <button class="button alert float-right" id="delete-card-btn" data-url="<%= card_path(@card) %>">Delete</button>

  </div>
</div>

app/views/cards/new.html.erb
<div class="grid-y">
  <div class="cell shrink title-cell">
    <h5 style="margin: 0">New Card</h5>
    <!--<button class="close-button" data-close aria-label="Close modal" type="button">-->
    <!--<span aria-hidden="true">&times;</span>-->
    <!--</button>-->
  </div>
  <div class="cell shrink" style="margin-top: 16px">

    <div class="input-group">
      <span class="input-group-label">Title</span>
      <input class="input-group-field" id="card-title" type="text" placeholder="Title">
    </div>

    <div class="input-group">
      <span class="input-group-label">Card type</span>
      <%= select_tag(:card_type, options_for_select([['Graph', 'graph'], ['Value', 'value']].prepend(['Select a type', '']), disabled: [''], selected: ['']), class: 'input-group-field') %>
    </div>

    <div class="input-group">
      <span class="input-group-label">Device</span>
      <%= select_tag(:device_id, options_for_select(current_user.devices.map {|device| [device.name, device.id]}.prepend(['Select a device', 0]), disabled: [0], selected: [0]), class: 'input-group-field') %>
    </div>

    <fieldset class="fieldset" style="margin-top: 0">
      <legend>Fields</legend>
      <div id="fields-boxes">
        No available fields
      </div>
    </fieldset>

    <button class="button" id="create-card-btn" data-url="<%= cards_path %>">Create</button>

  </div>
</div>